spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gamecatalog}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always